### ISSUE TITLE
Problemas de compilación

### ISSUE THREAD

**Issue by neon520** [JJ/cv#1]
Estoy intentando hacer mi curriculum con tu plantilla y me salta a la hora de compilarlo el siguiente error:

  ! Missing } inserted.
  <inserted text> 
                  }
  l.28   \entry

y donde me salta es tal que así:

\section{Habilidades}
\begin{entrylist}
  \entry
    {Terminar proyectos en el plazo previsto}
  \entry
    {Aprender fácilmente un lenguaje de programación en poco tiempo}
  \entry
    {Facilidad de adaptación frente a un grupo de trabajo}
\end{entrylist}

No se bien por qué puede ser la verdad, he investigado por ahí y no sé a qué se debe. El tema tildes no es porque por probar si era eso o no se las quité.

EDIT:
Aquí dejo enlace a mi [código](https://github.com/neon520/cv/blob/master/cv.tex)

EDIT2:
Ya he descubierto de donde provenía todo, venía de la definición de entry, cierro el issue

**Comment by JJ** [comment]
¿eso es que lo has arreglado?
